### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/odd-order#22]
Since #21 has been merged, @erikmd

**Comment by erikmd** [comment]
Indeed, sorry @CohenCyril, maybe this is the usual "pull_request vs. push" issue (as the initial commit of my PR was a bit old and the push workflow didn't attempt to do a merge beforehand)

I can't have a look just now but I guess the issue might be solved just by bumping the mathcomp image versions in the `coq-action.yml` file (e.g. by removing mathcomp 1.10.0 as it seems not to be compatible anymore, and enabling/un-commenting the other lines)

**Comment by erikmd** [comment]
@CohenCyril I guess this issue #22 is fixed by your PR #23 (I don't have the rights to close it)

**Comment by CohenCyril** [comment]
fixed by #23 indeed
