### ISSUE TITLE
Build failure with master version of math-comp

### ISSUE THREAD

**Issue by vbgl** [math-comp/odd-order#4]
Here is the error message:

~~~
File "./theories/PFsection3.v", line 580, characters 55-61:
Error:
Syntax error: '<-' expected after [Prim.name] (in [constr:operconstr]).
~~~

**Comment by SkySkimmer** [comment]
I guess there's a conflict with this recent addition: https://github.com/math-comp/math-comp/pull/217/files#diff-f0a7587e177819ca3c25c4986fc6dc08R2881
